name: "Scan-code"

on:
  push:
    branches:    
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  Code-Build:

    strategy:
      fail-fast: true


    # CodeQL runs on ubuntu-latest, windows-latest, and macos-latest
    runs-on: Ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
         languages: C++
        
    # Autobuild attempts to build any compiled languages  (C/C++, C#, or Python).
    # If this step fails, then you should remove it and run the build manually (see below)
    - name: Automatic
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
